from Voicelab.pipeline.Node import Node
from parselmouth.praat import call
from Voicelab.toolkits.Voicelab.VoicelabNode import VoicelabNode

###################################################################################################
# MEASURE DURATION NODE
# WARIO pipeline node for measuring the duration of a voice.
###################################################################################################
# ARGUMENTS
# 'voice'   : sound file generated by parselmouth praat
###################################################################################################
# RETURNS
# 'Voice Duration'  : Length of the voice file in miliseconds
###################################################################################################


class MeasureDurationNode(VoicelabNode):

    ###############################################################################################
    # process: WARIO hook called once for each voice file.
    ###############################################################################################
    def process(self):
        try:
            """Returns the total duration of a sound file."""
            voice = self.args["voice"]
            duration: float = call(voice, "Get total duration")

            return {"Voice Duration": duration}
        except:
            return {"Voice Duration": "Measurement failed"}