from Voicelab.pipeline.Node import Node
from parselmouth.praat import call
from Voicelab.toolkits.Voicelab.VoicelabNode import VoicelabNode


# MANIPULATE PITCH NODE
# WARIO pipeline node for manipulating the pitch of a voice.
# ARGUMENTS
# 'voice'   : sound file generated by parselmouth praat
# RETURNS


class ResampleSoundsNode(VoicelabNode):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.args = {"Sampling Rate": 44100,  # Positive number
                     "Precision": 50    # Positive integer
                     }
        # process: WARIO hook called once for each voice file.

    def process(self):
        # Load arguments
        sound = self.args["voice"]
        sampling_rate = self.args["Sampling Rate"]
        precision = self.args["Precision"]
        file_path = self.args["file_path"]

        # resample sound
        sound = sound.resample(sampling_rate, precision)

        # set up file name
        output_file_name: str = file_path.split("/")[-1].split(".wav")[0]
        output_file_name = f"{output_file_name}_resampled_to_{sampling_rate}_Hz"
        sound.name = output_file_name

        return {"voice": sound}
