from Voicelab.pipeline.Node import Node
from parselmouth.praat import call
from Voicelab.toolkits.Voicelab.VoicelabNode import VoicelabNode


# MANIPULATE PITCH NODE
# WARIO pipeline node for manipulating the pitch of a voice.
# ARGUMENTS
# 'voice'   : sound file generated by parselmouth praat
# RETURNS


class ReverseSoundsNode(VoicelabNode):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.args = {}
        # process: WARIO hook called once for each voice file.

    def process(self):
        sound = self.args["voice"]
        file_path = self.args["file_path"]
        sound.reverse()
        output_file_name = file_path.split("/")[-1].split(".wav")[0]
        output_file_name = f"{output_file_name}_reversed"
        sound.name = output_file_name

        return {"voice": sound}
